### ISSUE TITLE
Wording surrounding function prototype scope in [dcl.type.reflexpr] (Needs NB Comment)

### ISSUE THREAD

**Issue by camio** [cplusplus/reflection-ts#11]
"If the reflexpr-operand designates an entity or alias at block scope
(6.3.3) or function prototype scope (6.3.4)"

There does not exist a "function prototype scope" in 6.3.4 nor
elsewhere in the IS and 6.3.4 was not touched by the reflection
working paper. In 6.3.4 of the IS we have a "Function parameter
scope", though.

**Comment by Axel-Naumann** [comment]
Resolved, @camio ?
