### ISSUE TITLE
[reflect.synopsis] 21.12.4.2: unpack_sequence_t is a variable template initialized by a type (Needs NB Comment)

### ISSUE THREAD

**Issue by Dani-Hub** [cplusplus/reflection-ts#17]
This is *not* a review deviation of the accepted [p0670r4](http://wg21.link/p0670r4) document but was observed during the review:

In [reflect.synopsis], the template `unpack_sequence_t` is defined as follows:
```
template <template <class...> class Tpl, ObjectSequence T>
constexpr auto unpack_sequence_t = unpack_sequence<Tpl, T>::type;
```
but according to [reflect.ops.objseq] p3:

> All specializations of unpack_sequence<Tpl, T> shall meet the TransformationTrait requirements
(23.15.1). The nested type named type is an alias to the template Tpl specialized
with the types in T.

So it seems that what `unpack_sequence_t` actually defines would be a type alias instead of a variable template and should be corrected to
```
template <template <class...> class Tpl, ObjectSequence T>
using unpack_sequence_t = typename unpack_sequence<Tpl, T>::type;
```

**Comment by Axel-Naumann** [comment]
Resolved, @camio ?
