### ISSUE TITLE
Editorial: Note A, B and C for Table 12 appear above the table

### ISSUE THREAD

**Issue by rogerorr** [cplusplus/reflection-ts#27]
Table 12 refers to "Note A, below" and likewise B and C; however the table 12 appears at the end of [dcl.type.reflexpr] in the PDF. (Sadly I don't know enough latex to know how to fix this.)

**Comment by hubert-reinterpretcast** [comment]
There are also specific formatting requirements. Using the 2018 version of the ISO/IEC Directives, Part 2; it appears that these have to be footnotes to the table, because those may contain requirements whereas plain notes to a table may not.
