### ISSUE TITLE
Missing typename for unpack_sequence_t

### ISSUE THREAD

**Issue by rogerorr** [cplusplus/reflection-ts#31]
The wording 18.11.2 [reflect.synopsis] for ```unpack_sequence_t``` is missing a ```typename``` (which was present in the proposed wording in http::/wg21.link/p1390r1)

In ```languagesupport.tex``` change:
```using unpack_sequence_t = unpack_sequence<Tpl, T>::type;```
to:
```using unpack_sequence_t = typename unpack_sequence<Tpl, T>::type;```

**Comment by zygoloid** [comment]
This `typename` is no longer necessary as of [P0634R3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0634r3.html).

**Comment by zygoloid** [comment]
Hmm, but the TS is based on an earlier C++ standard that doesn't contain that.

**Comment by rogerorr** [comment]
Yes, the age of the base document is a difficulty, isn't it?!
