### ISSUE TITLE
Concept case

### ISSUE THREAD

**Issue by hatcat** [cplusplus/reflection-ts#34]
In 18.11.3 the concepts are named using CamelCase. Since Cologne (I forget the paper number) concepts now use snake_case. Perhaps this new style should be... reflected... in this clause.

**Comment by hatcat** [comment]
I'm not even slightly sorry for that pun.

**Comment by hubert-reinterpretcast** [comment]
This is technically not editorial. I am sympathetic though.

**Comment by hatcat** [comment]
Understood. Thank you.
