### ISSUE TITLE
struct is_thread_local missing template parameter?

### ISSUE THREAD

**Issue by hatcat** [cplusplus/reflection-ts#36]
I may be misunderstanding the work here, but I note that is_thread_local at [reflect.synopsis] and 18.11.4.9 para 2 is missing the template parameter from their declaration. Is this intentional?

**Comment by Axel-Naumann** [comment]
The other templates around it are constrained redeclarations of an earlier unconstrained declaration and thus need the template parameter, while `is_thread_local` is a template declaration.

**Comment by camio** [comment]
Yes, exactly as Axel sated. One is a specialization and the other is a declaration.
