### ISSUE TITLE
Reference to C++ Standard should be dated

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/reflection-ts#37]
Since the stated intent is to use C++14 as the base, the reference in [intro.refs] should be to "ISO/IEC 14882:2014".

**Comment by camio** [comment]
I had it as that originally, but changed it. There was some worry that it might flag an issue with ISO mentioning the older C++ standard.

**Comment by hubert-reinterpretcast** [comment]
I think its harmless in terms of technical content (the Clause numbers are clearly the C++14 ones); however, the use case that comes to mind is that some shells $$ :dollar: for the TS, and then shells $$$ :moneybag:  for C++17 (or C++20) only to find they needed C++14. If we're worried about ISO flagging this, they might notice the old-style clause numbering (e.g., Clause 3 is not the terms and definitions) faster than the date.
