### ISSUE TITLE
C++14 rebase changes lambda capture behaviour

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/reflection-ts#39]
Something or another about the result of the meta-object operations upon `metatype` below differs between the rebased draft and the draft approved in Cologne. If the implicit capture occurs with the inner lambda, then the type of the member is `const`, and the closure type associated with the capture is not that of the outer lambda. Although the base text for the relevant PDTS wording is gone, I believe the ability to attach to that base text was merely a wording convenience.

```cpp
auto f(void) {
  int x = 0;
  auto &&lambda = [x](void) mutable {
    // x is not implicitly captured by the lambda enclosing reflexpr under the
    // new draft; however, x does refer to an entity captured by copy.
    return [=] { return static_cast<reflexpr(x) *>(0); }();
  };
  return lambda();
}

using metatype = decltype(*f());
```

**Comment by camio** [comment]
Do you have a concrete suggestion for how to address this?

**Comment by hubert-reinterpretcast** [comment]
I believe the following would help capture the intent; however, correctness might require CWG review.

Add to the end of C++14 subclause 5.1.2 [expr.prim.lambda] paragraph 12:
> where, for the process of this determination, `reflexpr` operands are not considered to be unevaluated operands.
