### ISSUE TITLE
Feature test macro (needs NB Comment)

### ISSUE THREAD

**Issue by camio** [cplusplus/reflection-ts#4]
> Roger: The TS should define a feature test macro. [I] propose _cpp_reflect as a suitable name and 201807 as a suitable value.

```
Insert new 4.3 between 4.2 and 4.3:

4.3 Feature-testing recommendations [intro.features]
1 An implementation that provides support for this Technical Specification
shall define the feature test
macro(s) in Table 2.

Table 2 — Feature-test macro(s)

Macro name Value
__cpp_reflect 201807
```

> Axel: That's a wonderful NB comment. Can you make sure it gets submitted?

> Roger: The BSI has already voted for the NWIP, but I can ensure it gets submitted
when we have the PDTS ballot

**Comment by Axel-Naumann** [comment]
Resolved - close, @camio ?
