### ISSUE TITLE
Ed, A.1 should not be a modification

### ISSUE THREAD

**Issue by Axel-Naumann** [cplusplus/reflection-ts#51]
I would argue that similarly to A.1 in Concepts TS, A.1 in Reflection TS should not be a directive to the editor but simply consist of the result:
> Compatibility [diff]
> A.1 C++ extensions for Reflection and ISO C++ 2014
> This subclause lists the differences between C++ with Reflection and ISO C++, by the chapters of this document.

I would also prefer to strike "Concepts" in the above paragraph, as "difference between C++ with Concepts and Reflection and ISO C++" is ambiguous, and as "extensions for Reflection" subsumes "extensions for Concepts".

**Comment by camio** [comment]
I don't think there is a clear guideline here and the current version is readable enough IMO. Closing, but feel free to reopen if you'd like further discussion on this.
