### ISSUE TITLE
Ed, A.1.1 should not be editing directives

### ISSUE THREAD

**Issue by Axel-Naumann** [cplusplus/reflection-ts#52]
IIUC, the Reflection TS "inherits" the compat part of Concepts TS, as its editing directives are based on top of those of the Concepts TS. As such, A.1.1. should not modify the text of N4641's A.1.1 but provide its own, just as N4641 does.

NOTE that the current wording mentions "Valid ISO C++ 2017", which should be C++2014.

Possible wording:
> **Affected subclause:** 2.12
> **Change:** New keywords.
> **Rationale:** Required for new features. The `reflexpr` keyword is added to introduce meta-data through a *reflexpr-specifier*.
> **Effect on original feature:** Any ISO C++ programs that used this keyword as identifiers are not valid C++ programs with Reflection.

**Comment by camio** [comment]
Closing per my comment on #51. Fixed the 2017 wording.
