### ISSUE TITLE
Ed, 17.6.1.3: header name "reflect" vs "reflection"

### ISSUE THREAD

**Issue by Axel-Naumann** [cplusplus/reflection-ts#53]
The rebasing changed `<experimental/reflect>` to `<exprimental/reflection>` (sic!). I believe we should keep the original name (including the proper spelling of "experimental" #30 ).

**Comment by camio** [comment]
Addressed by resolution to #30.

**Comment by hubert-reinterpretcast** [comment]
We can close this.
