### ISSUE TITLE
No instruction to apply Concepts TS in the rebased document

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/reflection-ts#57]
There needs to be an instruction to apply the Concepts TS as opposed to merely mentioning that the Concepts TS exists.

**Comment by camio** [comment]
Can you suggest some wording for this?

**Comment by hubert-reinterpretcast** [comment]
Putting some wording in a "convenient place" (also, making a drive-by fix re: [intro.namespace] caused by mixing core language TS and library TS structure):

In subclause 1.4 [intro.compliance] add a new paragraph before the current paragraph 1:
Apply the modifications specified by the Concepts-TS. Further, add the contents of subclause 1.5 [intro.namespace] as a new subclause to subclause 17.6.1 [organization] of the C++ Standard.

**Comment by Axel-Naumann** [comment]
Shouldn't this be handled as part of the review? We have rebased the TS, the issue here is part of the rebasing. Suggest modification of 1.1(2):

> The International Standard, ISO/IEC 14882, together with the C++ Extensions for Concepts,  ISO/IEC TS 19217:2015, provide important context [...] This document is written as a set of changes against the specification of ISO/IEC 14882, as modified by C++ Extensions for Concepts, ISO/IEC TS 19217:2015.
