### ISSUE TITLE
18.11.3.33, Lambda should be true when reflecting type not object

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/reflection-ts#67]
18.11.3.33 [reflect.concepts.lambda] states that a meta-object that reflect a closure object satisfies `Lambda`. This should probably say "type" in place of "object".

**Comment by camio** [comment]
I'm not sure this is true. Axel, what are your thoughts?

**Comment by hubert-reinterpretcast** [comment]
A `Lambda` is a `Scope`. Applying `reflexpr` to a lambda capture something that is done in the body of a lambda expression. Applying `get_scope` on the result of such supposedly gives back a `Lambda`. The runtime object associated with said `Lambda` is far from clear.
