### ISSUE TITLE
18.11.4.10: Base reflecting incomplete type should be impossible

### ISSUE THREAD

**Issue by hubert-reinterpretcast** [cplusplus/reflection-ts#85]
The meta-object operations that produce meta-objects satisfying `Base` require complete types, which would require the base classes to be complete.

**Comment by camio** [comment]
AN: I do not understand this issue. A Base is not reflecting a type; it is
reflecting the fact that some class derives from another class. If this is an
issue (which I currently do not understand) then it would probably be an issue
(erm) and should not be part of the editorial review.

**Comment by camio** [comment]
Left open as an issue to handle post-publication.

**Comment by hubert-reinterpretcast** [comment]
The issue is a minor one pointing out that the requirement in reflect.ops.derived:
A specialization of any of these templates with a meta-object type that is reflecting an incomplete type renders the program ill-formed.

is redundant with the same requirement in reflect.ops.record.
